.\" Copyright (c) 2020 Omar Polo <op@omarpolo.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate: October 2 2020$
.Dt TANGO 1
.Os
.Sh NAME
.Nm tango
.Nd tagle gemini files
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl r Ar regex
.Op Fl o Ar out
.Op files...
.Ek
.Sh DESCRIPTION
.Nm
exports blocks of code from text/gemini files.
.Pp
.Nm
is able to export only the preformatted blocks whose alternative text
matches
.Ar regex .
.Pp
By default
.Nm
reads from standard input and writes to standard output, if no
.Ar out
or
.Ar file
are given.
.Pp
The regex is matched ignoring the case.
